export const LOAD_MORE_HOMES = 'LOAD_MORE_HOMES';
export const LOADING_MORE_HOMES = 'LOADING_HOMES';
export const REFRESHING_SEARCH = 'REFRESHING_SEARCH';
export const REFRESH_SEARCH = 'REFRESH_SEARCH';
export const UPDATE_FACETS = 'UPDATE_FACETS';
